name: Build and Push Pages Branch

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: gradle


      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean composeApp:jsBrowserDistribution

      - name: Copy stickers into dist
        run: |
          OUTPUT=composeApp/build/dist/js/productionExecutable
          if [ -d stickers ]; then
            cp -r stickers "$OUTPUT/"
          fi

      

      - name: Configure git as GitHub Bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push build output to pages branch
        run: |
          OUTPUT=composeApp/build/dist/js/productionExecutable
          BRANCH=pages

          git checkout --orphan $BRANCH
          git rm -rf .

          cp -r "$OUTPUT"/* .

          git add .
          git commit -m "chore: deploy pages"
          git push -f origin $BRANCH
